sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t wnstlr0615/react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true wnstlr0615/react-app npm run test -- --coverage

after_success:
 - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-288435180657"
  bucket_path: "elasticbeanstalk-ap-northeast-2-288435180657"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
