version: "3"
services: 
  react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
     - "3000:3000"
    volumes: 
     - /usr/src/node_modules
     - ./:/usr/src
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
     - /usr/src/node_modules
     - ./:/usr/src
    command: ["npm", "run", "test"]
